
# inspired by:
# https://mherman.org/blog/dockerizing-a-react-app/

version: '3.7'
services:

  dev:
    container_name: dev_container
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  make-build-folder:
    container_name: make-build-folder_container
    build:
      context: .
      dockerfile: Dockerfile-make-build-folder
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=production

  build-and-deploy:
    container_name: build-and-deploy_container
    build:
      context: .
      dockerfile: Dockerfile-build-and-deploy
    environment:
      - NODE_ENV=production

  build-only:
    container_name: build-only_container
    build:
      context: .
      dockerfile: Dockerfile-build-only
    environment:
      - NODE_ENV=production
